const {addflightsch,removeflight,cancelsch,searchflight,getairline,addflight,getflight,getfare,getsch,getflightbyfid,updateflight,getschedule,updateschedule}=require('./flight.controller');
const router=require('express').Router();
const {checkToken}=require('../../auth/tokenvalidation');
router.post("/addsch",checkToken,addflightsch);
router.get("/search",checkToken,searchflight);
router.delete("/remove/:id",checkToken,removeflight);
router.delete("/removesch/:schid",checkToken,cancelsch);
router.post("/cancelsch",checkToken,cancelsch);
router.get("/getairline",checkToken,getairline);
router.get("/getflight",checkToken,getflight);
router.post("/addflight",checkToken,addflight);
router.get("/getfare",checkToken,getfare);
router.get("/getsch",checkToken,getsch);
router.get("/getflightbyfid/:fid",checkToken,getflightbyfid);
router.get("/getschedule/:schid",checkToken,getschedule);
router.post("/updateflight",checkToken,updateflight);
router.post("/updateschedule",checkToken,updateschedule);
module.exports = router;