const {addflightsch,removeflight,cancelsch,searchflight,getairline,addflight,getflight}=require('./flight.controller');
const router=require('express').Router();
const {checkToken}=require('../../auth/tokenvalidation');
router.post("/addsch",checkToken,addflightsch);
router.get("/search",checkToken,searchflight);
router.delete("/remove/:id",checkToken,removeflight);
router.post("/cancelsch",checkToken,cancelsch);
router.get("/getairline",checkToken,getairline);
router.get("/getflight",checkToken,getflight);
router.post("/addflight",checkToken,addflight);
module.exports = router;