const {createUser,getuserbyemail,logout,getusername,checkemail,updatestatus,updateadmin}=require('./user.controller');
const router=require('express').Router();
const {checkToken}=require('../../auth/tokenvalidation');
router.post("/signup",createUser);
router.post("/adminsignup",checkToken,createUser);
router.post("/login",getuserbyemail);
router.post("/logout",logout);
router.get("/getname",checkToken,getusername);
router.get("/checktoken/:token",checkemail);
router.get("/updatestatus/:uid",updatestatus);
router.post("/updateadmin",updateadmin);
module.exports = router;
